// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1yxLlgyb_s4PQHKxIBHy12SPEARwDeBU',
    appId: '1:519843977308:web:6425a292826c0985366e99',
    messagingSenderId: '519843977308',
    projectId: 'demo1-1016a',
    authDomain: 'demo1-1016a.firebaseapp.com',
    storageBucket: 'demo1-1016a.appspot.com',
    measurementId: 'G-8VTE4XXDDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamC3sDTRSABcfRCCbwKsHJ7H_k1sfRpc',
    appId: '1:519843977308:android:b60002a86793771b366e99',
    messagingSenderId: '519843977308',
    projectId: 'demo1-1016a',
    storageBucket: 'demo1-1016a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTpq4o2fbSae7SSQoU3fmqq4zBkM8m3FU',
    appId: '1:519843977308:ios:e91cf9a118d45e28366e99',
    messagingSenderId: '519843977308',
    projectId: 'demo1-1016a',
    storageBucket: 'demo1-1016a.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTpq4o2fbSae7SSQoU3fmqq4zBkM8m3FU',
    appId: '1:519843977308:ios:e91cf9a118d45e28366e99',
    messagingSenderId: '519843977308',
    projectId: 'demo1-1016a',
    storageBucket: 'demo1-1016a.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1yxLlgyb_s4PQHKxIBHy12SPEARwDeBU',
    appId: '1:519843977308:web:67e54bfe33ac957a366e99',
    messagingSenderId: '519843977308',
    projectId: 'demo1-1016a',
    authDomain: 'demo1-1016a.firebaseapp.com',
    storageBucket: 'demo1-1016a.appspot.com',
    measurementId: 'G-LT5RFM9TGY',
  );
}
